### ISSUE TITLE
SynthDefs not found in Linux

### ISSUE THREAD

**Issue by gilfuser** [snappizz/BBCut2#10]
Hi,
I'm having problems running the examples in Linux Ubuntu Studio. Maybe something is wrong regarding the installation.
The errors are like so:
// first example, first error
Automated FX unit swapping
*** ERROR: SynthDef cb3playbuf2 not found
FAILURE IN SERVER /s_new SynthDef not found
...

In the sqpush on sqpush example:
*** ERROR: SynthDef cb2playbuf2 not found
FAILURE IN SERVER /s_new SynthDef not found
FAILURE IN SERVER /n_set Node 1008 not found
...

//simultaneous beat tracking and event analysis and beat tracking stereo remix. The first part of the example works. When I do the
'a=','b=', etc, I get the errors I collected below, plus "Node xxxx not found"
 *** ERROR: SynthDef analyseeventsdatabase1 not found
 *** ERROR: SynthDef cutmixer1 not found
*** ERROR: SynthDef cs1playbuf1 not found

Do you have any idea of what going on?
In Windows everything is working fine

best regards,
Gil

**Comment by nhthn** [comment]
weird, `\cb3playbuf2` should be defined here: https://github.com/snappizz/BBCut/blob/master/classes/cutsynths/CutBuf3.sc

first we should check whether `SynthDef.new` is getting called at all. can you try putting a `"hi".postln` right before `SynthDef(\cb3playbuf...)` line?

**Comment by gilfuser** [comment]
I did it. In the class CutBuf3.sc, in the line 21. It's that right? If it is, that means that SynthDef.new is not being called.

**Comment by nhthn** [comment]
that means the problem might be with `StartUp.add`. please try this dummy class:

```supercollider
FooBar {
    *initClass {
        StartUp.add({
            "hi".postln;
        })
    }
}
```

if the post doesn't go through, then there's probably another quark that's messing with `StartUp`.

**Comment by gilfuser** [comment]
Yes, something was messing with StartUp. I had a folder in Extension which
were causing an error during the startup. I thought it was harmless. Was
the folder with SCVim (I never used, it was there just to try it someday).

Well, case solved! Thank you!

Best regards,
Gil

Nathan Ho <notifications@github.com> schrieb am Di., 28. Feb. 2017 um
21:58 Uhr:

**Comment by nhthn** [comment]
great!
